### ISSUE TITLE
Install shouldn't enable services automatically

### ISSUE THREAD

**Issue by pesho** [zyga/snapd-arch#3]
The install script automatically enables and starts `snapd.refresh.timer` and `snapd.socket`. This is the usual practice on Debian / Ubuntu, but is not an established practice on Arch. The usual way is to just print instructions on the console and let the user enable these services if they choose so.

**Comment by pesho** [comment]
The same should apply for upgrades. Don't restart the service automatically, just print an instruction to do so.

I realize that doing these automatically might be seen as more user-friendly, but I think it's more important to follow the established practices of the targeted distro (Arch).

**Comment by timjp87** [comment]
This should be fixed with #5.

**Comment by zyga** [comment]
This is now fixed by #5
